export const Strings = {
  available: "Available",
  address: "Address",
  amount: "Product Amount",
  buy: "Buy",
  basefee: "Base fee",
  cvv: "CVV",
  creditNumber: "Card Number",
  city: "City",
  complement: "Complement",
  document: "Document",
  department: "Department",
  delivery: "Delivery",
  datetrx: "Transaction Date",
  deliveryinfo: "Delivery Information",
  email: "E-mail",
  expiry: "Expiry",
  gopay: "Go to Pay",
  holderName: "Holder Name",
  ip: "IP Transaction",
  idtrx: "ID Transaction",
  lastnameDelivery: "Lastname",
  noUnits: "Units no Availables",
  nameDelivery: "Name",
  phone: "Phone",
  placeholderemail: "example@example.com",
  product: "Product",
  products: "Products",
  paymethod: "Payment Method",
  pay: "Pay",
  quantity: "Quantity",
  returnStore: "Return to Store",
  select: "Select",
  subtotal: "Subtotal",
  summary: "Summary",
  total: "Total",
  type: "Type",
};