export const Strings = {
  available: "Available",
  address: "Address",
  amount: "Product Amount",
  buy: "Buy",
  basefee: "Base fee",
  cvv: "CVV",
  creditNumber: "Card Number",
  city: "City",
  complement: "Complement",
  declined: 'DECLINED',
  document: "Document",
  document_Delivery: "Document Delivery",
  document_Customer: "Document Customer",
  department: "Department",
  delivery: "Delivery",
  datetrx: "Transaction Date",
  deliveryinfo: "Delivery Information",
  email: "E-mail",
  expiry: "Expiry",
  gopay: "Go to Pay",
  holderName: "Holder Name",
  ip: "IP Transaction",
  idtrx: "ID Transaction",
  lastnameDelivery: "Lastname",
  lastname_delivery: "Lastname Delivery",
  lastname_customer: "Lastname Customer",
  noUnits: "Units no Availables",
  name_customer: 'Name Customer',
  name_delivery: 'Name Customer',
  nameDelivery: "Name",
  phone: "Phone",
  placeholderemail: "example@example.com",
  product: "Product",
  products: "Products",
  paymethod: "Payment Method",
  pay: "Pay",
  pending: 'PENDING',
  success: "APPROVED",
  error: "ERROR",
  quantity: "Quantity",
  returnStore: "Return to Store",
  select: "Select",
  subtotal: "Subtotal",
  summary: "Summary",
  trx_success: "Transaction Success",
  trx_declined: "Transaction Declined",
  transaction_status: 'Transaction Status',
  total: "Total",
  type: "Type",
  img_success: "https://cofintec.com/img/chulo.png",
  img_faild: "https://img.freepik.com/psd-gratis/marca-cruz-aislada_23-2151478803.jpg"
};